#ifndef MEGADEV__ECHO_DEF_H
#define MEGADEV__ECHO_DEF_H

#define ECHO_CMD_LOAD_LIST 1
#define ECHO_CMD_PLAY_SFX 2
#define ECHO_CMD_STOP_SFX 3
#define ECHO_CMD_PLAY_BGM 4
#define ECHO_CMD_STOP_BGM 5
#define ECHO_CMD_RESUME_BGM 6
#define ECHO_CMD_SET_PCM_RATE 7
#define ECHO_CMD_PAUSE_BGM 8
#define ECHO_CMD_SET_STEREO 9

#endif
