#!/usr/bin/env python3
"""Generate the lookup tables for the pseudo-3D ground plane.

Two tables, both indexed by output row, plus one sine table.

    zf[r]   the ground distance for row r, in xform_pos units (1/8 dot)
    zk[r]   that same distance times the horizontal scale, in step units
            (1/2048 of a source dot per output pixel)
    sin[a]  sine, Q15, over a full turn

Why tables at all: the perspective relation is z = K / d, one divide per row
per frame, and the 68000's divu is slow. d depends only on the row, so z can be
computed once, here, and read at runtime. The same applies to sin and cos.

The step ceiling is checked here rather than discovered on hardware. The trace
vector step format has four integer bits, so a magnitude of 16.0 or more
overflows into the sign bit and the row renders as garbage in the opposite
direction. Sonic CD's own special stage runs to about 14.6, so there is very
little headroom -- see docs/rotation_scaling.md section 7.2.
"""

import math
import sys

SCREEN_W = 256          # output width in dots
ROWS = 128              # rows of ground drawn, top (far) to bottom (near)
HORIZON_GAP = 24        # rows between the true horizon and the first drawn row
CAMERA_K = 22000        # combined camera height and focal length
H_SCALE = 1.7           # horizontal field of view

POS_SCALE = 8           # xform_pos: Q13.3
STEP_SCALE = 2048       # xform_delta: Q4.11
STEP_MAX = 16.0
SIN_ENTRIES = 256


def build():
    zf, zk, worst = [], [], 0.0
    for r in range(ROWS):
        d = r + HORIZON_GAP              # distance below the horizon, never 0
        z = CAMERA_K / d                 # ground distance for this row
        step = z * H_SCALE / SCREEN_W    # source dots per output pixel

        worst = max(worst, step)
        if step >= STEP_MAX:
            sys.exit(f"row {r}: step {step:.2f} exceeds the {STEP_MAX} ceiling.\n"
                     f"Raise HORIZON_GAP or lower CAMERA_K/H_SCALE.")

        zf.append(int(z * POS_SCALE) & 0xFFFF)
        zk.append(int(step * STEP_SCALE))

    sin = [int(round(math.sin(i * 2 * math.pi / SIN_ENTRIES) * 32767)) & 0xFFFF
           for i in range(SIN_ENTRIES)]
    return zf, zk, sin, worst


def words(name, vals, per_line=8):
    out = [f"GLABEL {name}"]
    for i in range(0, len(vals), per_line):
        out.append("\t.word\t" + ", ".join(f"0x{v:04X}" for v in vals[i:i + per_line]))
    return "\n".join(out)


def main():
    zf, zk, sin, worst = build()
    print(f"generated: {ROWS} rows, worst step {worst:.2f} of {STEP_MAX} "
          f"({worst / STEP_MAX * 100:.0f}% of the ceiling)", file=sys.stderr)

    with open("src/tables.s", "w") as f:
        f.write(f"""/**
 * Lookup tables for the pseudo-3D ground plane.
 *
 * GENERATED by tools/gen_tables.py -- do not edit by hand.
 *
 * rows {ROWS}, horizon gap {HORIZON_GAP}, camera K {CAMERA_K}, h scale {H_SCALE}
 * worst step {worst:.2f} of a {STEP_MAX} ceiling
 */
.section .rodata
#include <macro.s>

/* Ground distance per row, in 1/8 dot units (xform_pos). */
{words("mode7_zf", zf)}

/* Step per row before rotation, in 1/2048 dot units (xform_delta). */
{words("mode7_zk", zk)}

/* sin(a) in Q15 over a full turn of {SIN_ENTRIES} steps. cos is the same table
 * read a quarter turn along, which is why there is no separate cosine table. */
{words("mode7_sin", sin)}
""")

    with open("src/tables.h", "w") as f:
        f.write(f"""/**
 * @file tables.h
 * @brief Generated lookup tables for the ground plane
 * GENERATED by tools/gen_tables.py -- do not edit by hand.
 */
#pragma once
#include <types.h>

#define MODE7_SCREEN_W {SCREEN_W}
#define MODE7_ROWS {ROWS}
#define MODE7_SIN_ENTRIES {SIN_ENTRIES}
#define MODE7_ANGLE_MASK (MODE7_SIN_ENTRIES - 1)
#define MODE7_COS_OFFSET (MODE7_SIN_ENTRIES / 4)

extern u16 const mode7_zf[MODE7_ROWS];
extern s16 const mode7_zk[MODE7_ROWS];
extern s16 const mode7_sin[MODE7_SIN_ENTRIES];
""")


if __name__ == "__main__":
    main()
