/**
 * @file tables.h
 * @brief Generated lookup tables for the ground plane
 * GENERATED by tools/gen_tables.py -- do not edit by hand.
 */
#pragma once
#include <types.h>

#define MODE7_SCREEN_W 256
#define MODE7_ROWS 128
#define MODE7_SIN_ENTRIES 256
#define MODE7_ANGLE_MASK (MODE7_SIN_ENTRIES - 1)
#define MODE7_COS_OFFSET (MODE7_SIN_ENTRIES / 4)

extern u16 const mode7_zf[MODE7_ROWS];
extern s16 const mode7_zk[MODE7_ROWS];
extern s16 const mode7_sin[MODE7_SIN_ENTRIES];
